### PR TITLE
[Issue_183] Do not use application.xml as the source of a deploymentName

### LINKED ISSUE #183: The `deploymentName` and the exported archive may have different names
In the `AppClientDeploymentPackager` the deployment name is first derived from the the `org.jboss.arquillian.container.test.spi.TestDeployment`. This is effectively the `@Deployment(name=)` attribute. It then looks in the EAR for a `application.xml`. If found and there is an entry for `<application-name/>`, that value is set to the deployment name. 

The deployment name is then set in the `AppClientProtocolConfiguration.setDeploymentName()` and used later when creating the appclient command with the `${deploymentName}` property.

However, when the `AppClientDeploymentPackager` exports the EAR to the file system, it uses the `EnterpriseArchive.getName()`. This archive is retrieved from the `TestDeployment.getApplicationArchive()`. This means the `getName()` effectively returns the `@Deployment(name=)` attribute again.

If the `<application-name/>` is defined in the deployment and is different than the deployment name, then the appclient file cannot be found the test will fail.

This is example output from WildFly running the EJB test `com.sun.ts.tests.ejb30.assembly.initorder.appclientejb.ClientTest#appName`
```
10:41:10,539 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 34) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "appclient")]): java.lang.RuntimeException: WFLYAC0023: Could not find application client /home/jperkins/projects/gitlab.cee.redhat.com/wildfly/jakartaee-tck-runners/jakarta-ee-tck-runners/enterprise-beans-platform-tck/enterprise-beans-platform-tck-runner/target/appclient/renamed2.ear
   at org.jboss.as.appclient@36.0.1.Final//org.jboss.as.appclient.subsystem.AppClientSubsystemAdd.performBoottime(AppClientSubsystemAdd.java:75)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractBoottimeAddStepHandler.performBoottime(AbstractBoottimeAddStepHandler.java:85)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractBoottimeAddStepHandler.performRuntime(AbstractBoottimeAddStepHandler.java:60)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:103)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1057)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:778)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:469)
   at org.jboss.as.controller@28.0.1.Final//org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:368)
   at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
   at java.base/java.lang.Thread.run(Thread.java:1583)
   at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

```

### PR DESCRIPTION
**Pull request by bstansberry**
Resolves #183

This also related to EE 11 TCK challenge https://github.com/jakartaee/platform-tck/issues/2670

### CODE REVIEW

**Comment by bstansberry** [comment]
Note that besides the test discussed in #183, the only other case I see in the EE 11 TCK of a deployment using the application.xml application-name element to change the EE application name is https://github.com/jakartaee/platform-tck/blob/jakartaeetck-11.0.1/tcks/apis/enterprise-beans/ejb30/src/main/java/com/sun/ts/tests/ejb30/assembly/initorder/warejb/application.xml

I don't know what effect this change would have on that test. WildFly passes that test without this change, but that's not surprising as it's not an appclient test. The #183 thing is a problem for appclient tests because the deploymentName is the only relevant value that can be used in the appclient process launch command to tell the process the name of the deployment file.

**Review by scottmarlow — APPROVED** [review]

**Comment by jhanders34** [comment]
Well the `deploymentName` was not added for the `clientCmdLineString` per se, but rather `clientStubsCmdLine`  in PR #180 for issue #179.  So it sounds like instead of making this change you have a need for a new `clientEarName` since your `clientCmdLineString` has a need to know the app client ear name whereas other vendors do not have that need.

**Review by jhanders34 — CHANGES_REQUESTED** [review]
See my previous comment for changes requested.

**Comment by scottmarlow** [comment]
@jhanders34 I added a commit that addresses your feedback.  Thanks for your help!

**Comment by scottmarlow** [comment]
Updated: For reference example arquillian.xml use of the new `clientEarName` property:

> <property name="clientCmdLineString">${jboss.home}/bin/appclient.sh;-y=${project.build.testOutputDirectory}/appclient-config.yml${path.separator}${project.build.testOutputDirectory}/ejb-config.yml;${clientEarDir}/${clientEarName}#$
> {clientAppArchive}
>

File: arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java [hunk 1]
```diff
@@ -74,6 +74,13 @@ public Archive<?> generateDeployment(TestDeployment testDeployment, Collection<P
         }
         log.info("Generating deployment for: " + deploymentName);
 
+        String clientEarName = testDeployment.getDeploymentName();
+        // The archive name does not match the @Deployment(name), so use the archive name as that is what a server will use
+        if(!archiveName.equals(clientEarName)) {
```
Comment (jhanders34) [inline arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java]: You have `archiveName` as `clientEarName.ear`.  

If `testDeployment.getDeploymentName()` doesn't have a `.ear` suffix, then this conditional will always be false.  

If it does have a `.ear` suffix, then if they match, then `clientEarName` will be set to a string that has a `.ear` suffix.  

So it is confusing logic to say the least.  I was actually surprised not to have `clientEarName` include the `.ear` suffix to begin with.  The ear name includes the file extension I would think.  It should be clearly documented what the format of the `clientEarName` field is.

**Review by jhanders34 — CHANGES_REQUESTED** [review]

File: arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java (hunk 1 above)
Comment (scottmarlow) [reply arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java]: Thanks @jhanders34 for the review and great feedback!  

I simplified the logic and ensured clientEarName includes the `.ear` suffix as well.  I also added an example `clientEarName` value and defined the format as well.

Comment (scottmarlow) [reply arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java]: The example and format is described above the `clientEarName` field in class `AppClientProtocolConfiguration`.

File: arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java [hunk 2]
```diff
@@ -74,6 +74,10 @@ public Archive<?> generateDeployment(TestDeployment testDeployment, Collection<P
         }
         log.info("Generating deployment for: " + deploymentName);
 
+        // clientEarName will be the EAR name for EAR deployments
+        String clientEarName = testDeployment.getDeploymentName().endsWith(".ear") ? testDeployment.getDeploymentName() : testDeployment.getDeploymentName() + ".ear";
```
Comment (jhanders34) [inline arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java]:
```suggestion
        String clientEarName = deploymentName.endsWith(".ear") ? deploymentName : deploymentName + ".ear";
```

**Review by jhanders34 — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks @bstansberry @jhanders34 !
